### ISSUE TITLE
comfoAir Checksum doesn't match

### ISSUE THREAD

**Issue by CommanderTux** [tieskuh/esphome-comfoair#2]
Just installed your version of "Zehnder WHR 950 ESPHOME".  And it works fine. But looking at the logs, I notice when getting fan status a warning that comfoAir Checksum doesn't match with the expected values.
This only occurs when the ventilation level (mode) is set to 'Low'. All other modes seem fine.

```
[20:59:53][D][comfoair:439]: getting fan status
[20:59:53][W][comfoair:267]: ComfoAir Checksum doesn't match: 0x48!=0xDB
..
[21:00:00][D][comfoair:439]: getting fan status
[21:00:00][W][comfoair:267]: ComfoAir Checksum doesn't match: 0x07!=0x36
..
[21:00:07][W][comfoair:267]: ComfoAir Checksum doesn't match: 0x40!=0x0F
[21:00:08][D][comfoair:447]: getting valve status
[21:00:10][D][comfoair:487]: getting ventilation level
[21:00:10][D][comfoair:362]: Level 02
```

It's not a real issue for me because everything seems to work fine.

btw, I'm using a WHR930!

Cheers,

Mark

**Comment by tieskuh** [comment]
Hi Mark,

I checked my logs again and the message doesn't appear in my logs. It might be a difference between the 930 and 950. I don't have access to a 930 to test it.

I see you also opened an issue at wichers component https://github.com/wichers/esphome-comfoair/issues/55

Might it be solved there, I can merge it.

**Comment by tieskuh** [comment]
Hi Mark,

I noticed @Megu fixed a checksum problem.  I copied his code, might fix your problem. https://github.com/Megu/esphome-comfoair/commit/0b76b2db6a6b1329e10a61080fd9586f254c4851

**Comment by CommanderTux** [comment]
Hi @tieskuh .

Thanks for the update. And thanks to @Megu, it seems that this patch indeed solved the minor issue with the checksum.

👏

**Comment by tieskuh** [comment]
Glad to hear it solved it!
