### ISSUE TITLE
Difference of WHR930/950 implementation? Support for Cooling unit?

### ISSUE THREAD

**Issue by m5ck** [tieskuh/esphome-comfoair#3]
Hi @tieskuh,

Thanks so much for extending the existing code to support the WHR930/950 units! Also thanks for the documentation and pictures in the readme!

Could you elaborate on what is different in the code that supports the WHR930/950 units, and perhaps add this information to the README? Does the WHR930/950 unit have the same/more/less features that you support in your code?

Also, I do have the luxe version of the WHR 950 (WHR 950 Luxe R) that comes with the Zehnder cooling unit (Artic 930) on top. Is that supported by the code as well? And if you have any ideas on how to access the serial port on the board in the center of the WHR 950 with the cooling unit Artic 930 on top of the WHR 950?

Also, I do have the ComfoControl CC Luxe Panel with the LCD display and RS485 bus. Any idea if that interferes with your code and can be run in parallel?

Finally, do you have any idea what the RJ45 connector next to your RS232 connector is for? 

Cheers!

![image](https://github.com/user-attachments/assets/c9481bf5-26a1-430b-b3c2-6e82f275276b)

**Comment by tieskuh** [comment]
Hi @mrtnkhl ,

Could you elaborate on what is different in the code that supports the WHR930/950 units, and perhaps add this information to the README? Does the WHR930/950 unit have the same/more/less features that you support in your code?

**Mainly some sensor readings that weren't correct in other versions if I remember correctly.**

Also, I do have the luxe version of the WHR 950 (WHR 950 Luxe R) that comes with the Zehnder cooling unit (Artic 930) on top. Is that supported by the code as well? And if you have any ideas on how to access the serial port on the board in the center of the WHR 950 with the cooling unit Artic 930 on top of the WHR 950?

**You can set the temperature, but cooling modes are not supported in this version.
You can try one of there versions: https://github.com/nyxnyx/esphome-comfoair or https://github.com/wichers/esphome-comfoair they seems to have some cooling features.
If you wish to use that version with the M5Stack, you would have to use this setting:**
```
uart:
  id: uart_bus
  rx_pin: 22
  tx_pin: 19
  baud_rate: 9600
```


Also, I do have the ComfoControl CC Luxe Panel with the LCD display and RS485 bus. Any idea if that interferes with your code and can be run in parallel?

**I'm not sure but please let me know if you find out so I can add that to the readme.**

Finally, do you have any idea what the RJ45 connector next to your RS232 connector is for?

**You can also use the RJ45 connector if you wish. Read about it here: https://github.com/tieskuh/esphome-comfoair/issues/1**

**Comment by m5ck** [comment]
Thanks @tieskuh!

If I understand correctly, neither the nyxnyx nor the wichers code will properly work with the WHR 950 since you had to modify the code on your end?

I will let you know what I find out about the RS485 situation, I tried to access the DB9 R232 on the controller board today and could not physically get to it. From what I read, the RS485 protocol is different to the RS232 protocol, see also https://community.home-assistant.io/t/ventilation-systems-comfoair-ca350-ca500-control-for-hass-zehnder-storkair-etc/18473/56

**Comment by tieskuh** [comment]
They will work. But for me, some sensors gave incorrect data and some controls weren't correct. But you should get readings.

From my understanding the RJ45 port also uses RS232: https://community.home-assistant.io/t/zehnder-comfoair-ca350-integration-via-serial-connection-rs232-and-mqtt/173243/434?u=mtulen888

Strange that you couldn't get to the DB9 port. Is it because the cooling unit is on top?

**Comment by m5ck** [comment]
That's right, the cooling unit is on top which makes it impossible to get to the control boards. At least from what I can tell trying to get to them. 

Do we know why they put an RJ45 and DB9 connector for RS232 on the same board?

**Comment by tieskuh** [comment]
No clue why..
If I remember correctly, you can also open the front and slide the control bord forward.

**Comment by m5ck** [comment]
I thought that would be possible but could not get it to move. There is a small screw that I removed but then I could not get the panel to move at all. How did you do that?

**Comment by tieskuh** [comment]
I think via the top cover :)

**Comment by m5ck** [comment]
Haha, I guess that would solve many problems if I could access it from the top! If you have a moment and pass by your unit with a screwdriver, it would be great to know if you get to slide the tray out without top access!

**Comment by tieskuh** [comment]
You have to remove a screw from the top before you can slide it out. I guess you have to remove your cooling unit…

**Comment by m5ck** [comment]
https://zehndernl.zendesk.com/hc/nl/articles/115005762889-WHR-950-960-RF-draadloos-maken

Looking at this manufacturers documentation on how to install the RF receiver, it seems to be one screw in the front. Where did you see the second screw?

**Comment by m5ck** [comment]
I talked to Zehnder this morning, they said there is only one screw in the front of the tray. The tray itself in the WHR950 config only contains one board with the RJ45 connector. When there is an Artic 930 (cooling unit on top) involved, there is another board further in the back on the same tray that is connected via the RJ45 on the first board.

Sliding the tray out fully is practically impossible because the cables coming from the upper Artic unit through the holes on top of the WHR 950 appear too short.
